spring:
  profiles:
    # 运行的环境
    active: prod
  application:
    name: duchat
  datasource:
    url: jdbc:mysql://${duchat.mysql.ip}:${duchat.mysql.port}/${duchat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${duchat.mysql.username}
    password: ${duchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      # Redis服务器地址
      host: ${duchat.redis.host}
      # Redis服务器端口号
      port: ${duchat.redis.port}
      # 使用的数据库索引，默认是0
      database: 0
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: ${duchat.redis.password}
  jackson:
    serialization:
      # 将 data 转化为时间戳
      write-dates-as-timestamps: true

wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    callback: ${duchat.wx.callback}
    configs:
      - appId: ${duchat.wx.appId} # 第一个公众号的appid
        secret: ${duchat.wx.secret} # 公众号的appsecret
        token: ${duchat.wx.token} # 接口配置里的Token值
        # aesKey: ${duchat.wx.aesKey} # 接口配置里的EncodingAESKey值，测试号不需要填

# jwt 密钥
duchat:
  jwt:
    secret: ${duchat.jwt.secret}
